### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by Tian-Hun** [hamzahamidi/ajsf#94] opened 2019-03-06 10:46 UTC
**Describe the bug**
which template:

* [X] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. [recurrent link](https://ng-notadd.notadd.net/elements/advanced-ui/json-schema-form)

**Desktop (please complete the following information):**

- OS: [macOS]
- Browser [Google Chrome]
- Version [72.0.3626.109]

- Angular version
![image](https://user-images.githubusercontent.com/22492312/53875533-a95be500-403f-11e9-9c08-2d3ecf93c871.png)

**Log output covering before error and any error statements**

```logs
Uncaught TypeError: Cannot read property 'endsWith' of undefined
```
![image](https://user-images.githubusercontent.com/22492312/53875254-19b63680-403f-11e9-98ac-a56da5d4387c.png)

**Comment by sverdlov** [comment] 2019-03-06 13:16
Duplicate of #73

**Closed** 2020-04-10 00:03 UTC
Labels: no-issue-activity
