### ISSUE TITLE
With data only, how do you keep showing the name of the field?

### ISSUE THREAD

**Issue by lamba92** [hamzahamidi/ajsf#95] opened 2019-03-12 10:40 UTC
I have a data JSON and I'm displaying it correctly. I just want to easily be able to keep showing the name of the field on the top using the material framework. Is that possible?

Furthermore, would it be possible to use the new outline layout?

**Comment by sverdlov** [comment] 2019-04-03 09:34
Duplicate of #91

**Closed** 2020-04-10 00:03 UTC
Labels: no-issue-activity
